##########################################################################
# Standard Properties
org.gradle.jvmargs = -Xmx2G
org.gradle.warning.mode = all
org.gradle.configuration-cache = false
##########################################################################
# Mod Properties
mod_version = 1.0.3
mod_group = net.colin
mod_name = younameit
##########################################################################
# Plugin Dependency
foojay_resolver_version = 1.0.0
##########################################################################
